## Introduction to numpy, pandas, and matplotlib

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
np, pd, plt

(<module 'numpy' from 'D:\\python\\lib\\site-packages\\numpy\\__init__.py'>,
 <module 'pandas' from 'D:\\python\\lib\\site-packages\\pandas\\__init__.py'>,
 <module 'matplotlib.pyplot' from 'D:\\python\\lib\\site-packages\\matplotlib\\pyplot.py'>)

## Numpy data types

## float32

In [3]:
x = np.float32(2 ** 17)
x, type(x)

(131072.0, numpy.float32)

## float64

In [4]:
x = np.float64(2)**1024
x, type(x)

C:\Users\joeyw\AppData\Local\Temp\ipykernel_20352\3357549316.py:1: RuntimeWarning: overflow encountered in double_scalars
  x = np.float64(2)**1024


(inf, numpy.float64)

## arrays have fixed datatype

In [5]:
lst=[1.,2.,3.,4.,5.]
array= np.array(lst)
array, type(array), array.dtype

(array([1., 2., 3., 4., 5.]), numpy.ndarray, dtype('float64'))

In [6]:
# np.arange creates array similar to how one would use a for loop or generator to make a list
start =0
end =100
interval= 10
range_array=np.arange(start,end+1,interval)
range_array

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

## Two dimensional lists and arrays

In [7]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
two_dim_array=np.array(list_of_lists)
two_dim_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
two_dim_array[0]

array([1, 2, 3])

In [10]:
for i in range(len(two_dim_array)):
    print(i)
    print(two_dim_array[i])

0
[1 2 3]
1
[4 5 6]
2
[7 8 9]


In [11]:
for i in range(len(two_dim_array)):
    row=two_dim_array[i]
    print("i j:")
    for j in range(len(row)):
        print(i,j)
        print(row[j])

i j:
0 0
1
0 1
2
0 2
3
i j:
1 0
4
1 1
5
1 2
6
i j:
2 0
7
2 1
8
2 2
9


## np.zeros, np.ones, np.empty
## np.zeros_like,np.ones_like, np.empty_like

In [12]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.empty((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
l = list_of_lists
np. zeros_like(1)

array(0)

In [16]:
np. ones_like((1))

array(1)

In [17]:
np. empty_like((1))

array(540156080)

## Log values

In [18]:
np. log(1)

0.0

In [19]:
np.log(np.e)

1.0

In [20]:
np.log(two_dim_array)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [21]:
np.log10(two_dim_array)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [22]:
pi = np.pi
e =np.e
lne =np.log(e)
infinity=np.inf
null_val=np.nan
pi,e,lne,infinity,null_val

(3.141592653589793, 2.718281828459045, 1.0, inf, nan)

## Pandas

In [23]:
data_dict = {"0 to 9": np.arange(10),
            "ones": np.ones(10),
            "zeros":np.zeros(10)}
data_dict

{'0 to 9': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'ones': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'zeros': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])}

In [24]:
df=pd.DataFrame(data_dict)
df

0 to 9  ones  zeros
0       0   1.0    0.0
1       1   1.0    0.0
2       2   1.0    0.0
3       3   1.0    0.0
4       4   1.0    0.0
5       5   1.0    0.0
6       6   1.0    0.0
7       7   1.0    0.0
8       8   1.0    0.0
9       9   1.0    0.0

In [25]:
# calling a single key will return a series
df[["0 to 9"]],type(df["0 to 9"])

(   0 to 9
 0       0
 1       1
 2       2
 3       3
 4       4
 5       5
 6       6
 7       7
 8       8
 9       9,
 pandas.core.series.Series)

In [26]:
# calling a list of keys will return a dataframe
df[["0 to 9"]]

0 to 9
0       0
1       1
2       2
3       3
4       4
5       5
6       6
7       7
8       8
9       9

In [27]:
df[["0 to 9", "ones"]]

0 to 9  ones
0       0   1.0
1       1   1.0
2       2   1.0
3       3   1.0
4       4   1.0
5       5   1.0
6       6   1.0
7       7   1.0
8       8   1.0
9       9   1.0

In [28]:
# calling by row
df.iloc[0]

0 to 9    0.0
ones      1.0
zeros     0.0
Name: 0, dtype: float64

In [29]:
# pandas may require you to use .loc to save the value in the specified location
df.loc[:3, "0 to 9"]

0    0
1    1
2    2
3    3
Name: 0 to 9, dtype: int32

In [30]:
# row indices can be strings becasue indices are keys. using df.loc[] allows you to call each row by name
df.T

0    1    2    3    4    5    6    7    8    9
0 to 9  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0
ones    1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
zeros   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [31]:
df.T.loc["0 to 9"]

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
Name: 0 to 9, dtype: float64

In [32]:
df.T.iloc[0]

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
Name: 0 to 9, dtype: float64

## Boolean arrays // Boolean series

In [33]:
df["0 to 9"]>3

0    False
1    False
2    False
3    False
4     True
5     True
6     True
7     True
8     True
9     True
Name: 0 to 9, dtype: bool

In [34]:
greater_than_3 = df["0 to 9"] > 3
greater_than_3

0    False
1    False
2    False
3    False
4     True
5     True
6     True
7     True
8     True
9     True
Name: 0 to 9, dtype: bool

In [35]:
df[greater_than_3]

0 to 9  ones  zeros
4       4   1.0    0.0
5       5   1.0    0.0
6       6   1.0    0.0
7       7   1.0    0.0
8       8   1.0    0.0
9       9   1.0    0.0

In [36]:
df[df["0 to 9"] > 3]

0 to 9  ones  zeros
4       4   1.0    0.0
5       5   1.0    0.0
6       6   1.0    0.0
7       7   1.0    0.0
8       8   1.0    0.0
9       9   1.0    0.0

## Using a Dictionary to Specify a DataFrame's Index
When you save arrays in a dictionary, they do not include any particular index. Instead, pandas creates a general index from 0 to one less than the length of the array. If you do not need a particular index, this can work.

It is often useful to create a dictionary and identify each value of interest individually. If you are a macroeconomist, you may, for example, collect data for “GDP”, “Real GDP”, the “Price Level”, and the quantity of “Money” (each key is in quotes). Below, we prepare a dictionary with values for years from 1990 to 2018.

In [37]:
import pandas as pd
import numpy as np
import random

macro_dict = {"GDP" : {},
             "Money" : {},
             "Real GDP" : {},
             "Price Level" : {}}

for key in macro_dict:
    for i in range(1990, 2018):
        macro_dict[key][i] = np.random.random() * 10000

print(macro_dict)

{'GDP': {1990: 8826.607936864877, 1991: 7656.309913909368, 1992: 9309.88665365393, 1993: 5492.890989513986, 1994: 4847.175499365244, 1995: 9911.08618373905, 1996: 630.6847553574446, 1997: 7522.311551973477, 1998: 8144.942690225607, 1999: 8787.510757443684, 2000: 2054.096322487333, 2001: 5927.797491585179, 2002: 7196.654944241014, 2003: 4987.951912194989, 2004: 5970.776530294089, 2005: 9670.533238421078, 2006: 327.1674762106469, 2007: 6967.6713477869225, 2008: 1147.1905669059945, 2009: 5293.396221364436, 2010: 9681.282941552552, 2011: 7299.011932685607, 2012: 642.6826398945174, 2013: 5931.588226166296, 2014: 91.40785480461267, 2015: 7293.512710681465, 2016: 5072.155917722118, 2017: 1133.6059008173195}, 'Money': {1990: 2943.7586994034805, 1991: 405.9110392017884, 1992: 3858.076858232692, 1993: 7079.79215203594, 1994: 7454.011944932959, 1995: 244.03331187081156, 1996: 9677.034761313884, 1997: 1205.0539646088332, 1998: 6794.401793585338, 1999: 6055.78889840562, 2000: 6332.007716313328, 200

In [38]:
macro_DF = pd.DataFrame(macro_dict)  
print(macro_DF)


              GDP        Money     Real GDP  Price Level
1990  8826.607937  2943.758699  9224.877333  4380.431341
1991  7656.309914   405.911039  4236.908253  5369.649471
1992  9309.886654  3858.076858  8061.606937  3741.828175
1993  5492.890990  7079.792152  1529.629866  3524.082252
1994  4847.175499  7454.011945     9.855839  4549.688643
1995  9911.086184   244.033312  6286.401909  4644.025929
1996   630.684755  9677.034761  7009.243356  9479.451453
1997  7522.311552  1205.053965  7880.905156  7761.144564
1998  8144.942690  6794.401794  1643.761771  8110.308950
1999  8787.510757  6055.788898  4124.236225   606.415832
2000  2054.096322  6332.007716  7456.325314  1655.102463
2001  5927.797492  9944.130390  9916.724324   182.617099
2002  7196.654944  4587.185278  3865.336585  4953.608562
2003  4987.951912  8026.425097  1320.905634  7959.585092
2004  5970.776530  3489.955756  1426.277935  2978.420961
2005  9670.533238  1624.388630  1950.774912  2570.748080
2006   327.167476  1448.460398 

In [39]:
Macro_DF[["GDP"]]

NameError: name 'Macro_DF' is not defined

In [ ]:
macro_DF["Velocity"] = macro_DF["GDP"] / macro_DF["Money"]
print(macro_DF)

In [ ]:
macro_DF.loc[1995:2000]

In [ ]:
macro_DF["Real GDP"].loc[1995:2000]

In [ ]:
macro_DF.plot()

## Matplotlib

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
macro_DF.plot.line(legend = "best")

In [ ]:
for key in macro_DF:
    macro_DF[key].plot.line()
    plt.title(key, fontsize = 20)
    plt.show()
    plt.close()

## Plotting the distribution of income

In [ ]:

income_data = pd.read_excel("https://www2.census.gov/programs-surveys/cps/tables/hinc-06/2019/hinc06.xls", header=[7])
income_data = income_data.rename(columns = {"Unnamed: 0": "Household Income"})

In [ ]:
income = income_data["Number"][1:-1].div(1000)
income.iloc[0] = 0
income.head()

In [ ]:
## brackets for income
income_levels = list(range(0, 201, 5))
income_levels.append(250)
income_levels = [str(i) + "k" for i in income_levels]
income_levels.append("250k+")
print(income_levels)

In [ ]:
# cumulative totals of every bracket combined
income_data = pd.DataFrame({"Income Level":np.array(income_levels),
                           "Households in Bracket":income})
income_data["Cumulative"] = income_data["Households in Bracket"].cumsum()
income_data = income_data.fillna(0).set_index("Income Level")
income_data.head()

In [ ]:
income_data= pd.DataFrame({"Income Level":np.array(income_levels),
                          "Households in Bracket":income})
income_data["Cumulative"] = income_data["Households in Bracket"].cumsum()
income_data.set_index("Income Level", inplace = True )
income_data

In [ ]:
total_households =income_data["Households in Bracket"].sum().round(3)
income_data["% in Bracket"] = income_data["Households in Bracket"].div(total_households.sum()).mul(100)
income_data["Cumulative %"] = income_data["% in Bracket"].cumsum().round(3)
income_data

In [ ]:
plt.rcParams.update({"font.size" : 16})
fig, ax = plt.subplots(figsize = (15, 7))
plot_df = income_data.dropna()
plot_df.plot.bar( 
                                 y=["% in Bracket","Cumulative %"],
                                 secondary_y = "Cumulative %", 
                                 fill=True, 
                                 alpha=.75, 
                                 width = .99,
    legend = True,
                                 ax=ax)
x_ticklabels =["$"+str(x) for x in plot_df.index]
ax.set_xticklabels(x_ticklabels)

y1_ticklabels =[str(y)+"%" for y in ax.get_yticks()]
ax.set_yticklabels(y1_ticklabels)

In [ ]:
plot_df.index

In [ ]:
new_index =[]
for ix in plot_df.index:
    new_index.append("$"+ix)
    
new_index

In [ ]:
income_25k_bin = income_data.loc[::5]
income_25k_bin.loc["250k+"]=income_data.iloc[-1]
income_25k_bin["Households in Bracket"] = income_25k_bin["Cumulative"].diff()
income_25k_bin